### ISSUE TITLE
Stops loading observations at 4k

### ISSUE THREAD

**Issue by hakkitakki** [HenryDeLange/inat-achievements#50]
Once it reaches 4k observations loaded, it displays "Calculating the Wild Achievements from the 0 new observations..." and loads indefinitely. Account used has 20k observations. Issue persisted after reloading and clearing cache. Tried it with another user's account(25k observations) and it also failed at around 4k. However an attempt on an account with 13k observations failed at 2.8k. Which would track with them all failing around 20% of observations loaded, but I don't know that I've tried enough to make that statement conclusively, so do with that bit what you will. 

Fails both in browser and on the desktop app. Browser used is google chrome

**Comment by HenryDeLange** [comment]
Thanks for logging an issue for this. It is likely a side effect of the fix I put in place to try and get around the 10k problem. I'll try to have a look at it this weekend.

If you can share the user account names that you tested with it might help with the investigation?

**Comment by hakkitakki** [comment]
> If you can share the user account names that you tested with it might help with the investigation?
hawkparty, birdwhisperer, and kuchipachi respectively

**Comment by HenryDeLange** [comment]
This issue should now be fixed as part of changes I made for #53. I tested with _hawkparty_ completely, and loaded the first 7000+ from _birdwhisperer_. It seems to be working now.
